tap "crisidev/chunkwm"
tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "d12frosted/emacs-plus"
tap "caskroom/cask"
brew "curl"
brew "pandoc"
brew "ripgrep"
brew "crisidev/chunkwm/chunkwm"
brew "d12frosted/emacs-plus/emacs-plus", args: ["with-no-title-bars"]
brew "koekeishiya/formulae/khd"
cask "karabiner-elements"
