#!/bin/bash

xhost +
xinit


wmname LG3D
# stalonetray &

feh --bg-scale ~/Pictures/9q4Odsw.jpg

dropbox start &

touchegg &

# compton &

# Remap caps lock to left control. This is not strictly speaking
# xmonad related, but it's handy if you're a vim user.
setxkbmap -option 'ctrl:no caps'

# Network manager, so we don't have to configure wifi at the command line.
if [ -z "$(pgrep nm-applet)" ] ; then
    nm-applet --sm-disable &
fi

# Set fallback cursor
xsetroot -cursor_name left_ptr

# New York Zip Code
xflux -z 10001

# Set keyboard repeat rate
xset r rate 200 60

# If Emacs is started in server mode, `emacsclient` is a convenient way to edit
# files in place (used by e.g. `git commit`)
export VISUAL=emacsclient
export EDITOR="$VISUAL"

# Finally launch emacs
exec dbus-launch --exit-with-session emacs --eval "(exwm-enable)"
