#!/bin/sh

xrdb ~/.Xresources
xset +fp ~/.fonts
xset fp+ /usr/share/fonts-font-awesome/font
xset fp+ /usr/share/fonts/ttf
xset fp rehash
wmname LG3D
stalonetray &

/opt/extras.ubuntu.com/variety/bin/variety &

dropbox start &

touchegg &

compton &

workspaces &

# Remap caps lock to left control. This is not strictly speaking
# xmonad related, but it's handy if you're a vim user.
setxkbmap -option 'ctrl:no caps'

# Network manager, so we don't have to configure wifi at the command line.
if [ -z "$(pgrep nm-applet)" ] ; then
    nm-applet --sm-disable &
fi

emacs &
