#! /bin/sh

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d "α" "β" "γ" "δ" "ε" "ζ"


desktop_config() {
	  bspc config $1 $2
	  for M in $(bspc query -M); do
		    bspc config -m $M $1 $2
	  done
}
desktop_config border_width 0
desktop_config window_gap 18


bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a mpv floating=on
bspc rule -a scratchpad floating=on  sticky=on
bspc rule -a rangerfloat floating=on
bspc rule -a lol floating=on
bspc rule -a .dmenuEextended_shellCommand.sh floating=on
wmname LG3D
