#!/bin/bash
# record screencast of a region into a gif using `byzanz-record`

# Delay before starting
DELAY=5

# Sound notification to let one know when recording is about to start (and ends)
beep() {
    paplay /usr/share/sounds/freedesktop/stereo/bell.oga &
}

printf "usage: rr [time] [file]\n"

# Duration and output file
if [ $# -gt 0 ]; then
    D="--duration=$@"
else
    echo Default recording duration 10s to $HOME/recorded.gif
    D="--duration=10 $HOME/rarecorded.gif"
fi

# # xrectsel from https://github.com/lolilolicon/xrectsel
# ARGUMENTS=$(xrectsel "--x=%x --y=%y --width=%w --height=%h") || exit -1

eval $(xwininfo -id $(xdotool getactivewindow) |
              sed -n -e "s/^ \+Absolute upper-left X: \+\([0-9]\+\).*/x=\1/p" \
                  -e "s/^ \+Absolute upper-left Y: \+\([0-9]\+\).*/y=\1/p" \
                  -e "s/^ \+Width: \+\([0-9]\+\).*/w=\1/p" \
                  -e "s/^ \+Height: \+\([0-9]\+\).*/h=\1/p" )
ARGUMENTS="--x=${x} --y=${y} --width=${w} --height=${h}"


echo Delaying $DELAY seconds. After that, byzanz will start
for (( i=$DELAY; i>0; --i )) ; do
    echo $i
    sleep 1
done
beep
byzanz-record --verbose --delay=0 ${ARGUMENTS} $D
beep
